start_conversation:
  description: >
    Based on your profile and the lead , write your initial introduction, including name, company, area of ​​interest and how we can help.  
  expected_output: >
    A friendly greeting of 1 sentences.
  agent: sdr