start_conversation:
  description: >
    Com base no seu perfil e no lead, escreva sua introdução inicial, incluindo nome, empresa, área de interesse e como podemos ajudar.  
  expected_output: >
    Uma saudação amigável de 1 frase.
  agent: sdr